name: 获取用户信息

on:
  # schedule:
  #   - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # 使用你设置的 secret
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run fetch script
        env:
          GET_ID_X_TOKEN: ${{ secrets.GET_ID_X_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          bun scripts/refresh-users.ts